import type { PublicProvider, StageTopic, StageSpec, StageCode, StageNode, StageAsset, StageLayout } from './stage-types';

// Authored teaching cutaways, not live agent adapters. Review: 2026-09-07.
const urls = {
  pi: 'https://github.com/earendil-works/pi/blob/main/packages/coding-agent/README.md',
  extensions: 'https://github.com/earendil-works/pi/blob/main/packages/coding-agent/docs/extensions.md',
  sessions: 'https://github.com/earendil-works/pi/blob/main/packages/coding-agent/docs/session-format.md',
  packages: 'https://github.com/earendil-works/pi/tree/main/packages',
  codex: 'https://learn.chatgpt.com/docs/codex/cli',
  agents: 'https://learn.chatgpt.com/docs/agent-configuration/agents-md',
  sandbox: 'https://learn.chatgpt.com/docs/agent-approvals-security',
  claude: 'https://code.claude.com/docs/en/memory',
  claudeHooks: 'https://code.claude.com/docs/en/hooks',
  claudePermissions: 'https://code.claude.com/docs/en/permissions',
  claudeCli: 'https://code.claude.com/docs/en/cli-reference',
  factory: 'https://docs.factory.ai/harness/agents-md',
  factoryHooks: 'https://docs.factory.ai/harness/hooks',
  factoryCli: 'https://docs.factory.ai/droid-cli/cli-reference',
  deepseek: 'https://api-docs.deepseek.com/guides/tool_calls/',
};

function code(file: string, language: string, text: string, provenance: StageCode['provenance'], sourceUrl: string, highlight: number[] = [1]): StageCode {
  return { file, language, text, provenance, sourceUrl, highlight };
}
const api = (file: string, language: string, text: string, sourceUrl: string, highlight?: number[]) => code(file, language, text, 'Documented API example', sourceUrl, highlight);
const pseudo = (file: string, text: string, sourceUrl: string, highlight?: number[]) => code(file, 'text', text, 'Illustrative pseudocode', sourceUrl, highlight);
const wire = (file: string, text: string, sourceUrl: string, highlight?: number[]) => code(file, 'json', text, 'Illustrative wire payload', sourceUrl, highlight);
const original = code('help.md', 'markdown', '# Welcomme\n\nFind answers in our [FAQ](./faq.md).\n', 'Workshop file', './workshop/help.md', [1, 3]);
const instructions = (file = 'AGENTS.md') => code(file, 'markdown', file === 'CLAUDE.md' ? "@AGENTS.md\n\nThe imported file contains the shared contract for this practice directory.\n" : "# Harness engineering practice task\n\nThis directory is a disposable teaching fixture, not a production project.\n\n- Read help.md and the current user task before editing.\n- The only allowed edit is one replacement of Welcomme with Welcome in help.md.\n- Preserve every other byte, including the FAQ link and trailing newline.\n- Preserve every other file. Do not add files or directories.\n- Do not edit verify.mjs, faq.md, README.md, AGENTS.md or CLAUDE.md.\n- If the starting document differs from the fixture, stop and report the mismatch.\n- Run `node verify.mjs` and report its exit code and the exact edit.\n- Do not commit, publish, access the network or change permission settings.\n\nThese instructions guide behavior; they do not install a permission boundary.\nThe learner runs an additional trusted verifier from outside this working copy.\n", 'Workshop file', `./workshop/${file}`, file === 'CLAUDE.md' ? [1] : [6, 7, 8]);
const verifier = code('verify.mjs · file-check excerpt', 'javascript', "const bytes = await readFile(join(root, name));\nif (name === 'help.md') {\nif (!bytes.equals(Buffer.from(expectedHelp))) {\nfailures.push('help.md: expected only Welcomme \u2192 Welcome; preserve all other bytes.');\n}\n} else if (name === 'verify.mjs') {\nif (!bytes.equals(await readFile(trustedScript))) {\nfailures.push('verify.mjs: differs from the trusted verifier being executed.');\n}\n} else {\nconst hash = createHash('sha256').update(bytes).digest('hex');\nif (hash !== protectedHashes[name]) failures.push(`${name}: protected file changed.`);\n}", 'Workshop file', './workshop/verify.mjs', [3, 7, 12]);
const diff = pseudo('help.md · expected diff', '- # Welcomme\n+ # Welcome\n\n  Find answers in our [FAQ](./faq.md).\n\nOnly the heading changes. The relative link is invariant.', './workshop/help.md', [1, 2, 4]);
const task = pseudo('workshop task · acceptance contract', 'Change: Welcomme → Welcome in help.md\nBoundary: preserve every other character\nInvariant: [FAQ](./faq.md) and faq.md unchanged\nIndependent evidence: node ../harness-starter/verify.mjs . exits 0\nIf the check fails: correct the file, then check again', './workshop/README.md', [1, 2, 3, 4]);

const pi = {
  packages: api('Pi packages · documented names, authored role map', 'json', '{\n  "model API": "@earendil-works/pi-ai",\n  "agent runtime": "@earendil-works/pi-agent-core",\n  "CLI + sessions + extensions": "@earendil-works/pi-coding-agent"\n}', urls.packages, [2, 3, 4]),
  before: api('.pi/extensions/workshop.ts · optional extension', 'typescript', 'import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";\n\nexport default function (pi: ExtensionAPI) {\n  pi.on("before_agent_start", (event) => ({\n    systemPrompt: event.systemPrompt +\n      "\\nWorkshop: preserve ./faq.md; verify the exact edit.",\n  }));\n}', urls.extensions, [4, 5, 6]),
  gate: api('.pi/extensions/workshop.ts · optional extension', 'typescript', 'import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";\n\nexport default function (pi: ExtensionAPI) {\n  pi.on("tool_call", (event) => {\n    if (event.toolName === "export_folder") {\n      return { block: true, reason: "Export is outside this task." };\n    }\n  });\n}', urls.extensions, [4, 5, 6]),
  result: api('.pi/extensions/inspect-result.ts · optional extension', 'typescript', 'import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";\n\nexport default function (pi: ExtensionAPI) {\n  pi.on("tool_result", (event) => {\n    if (event.toolName === "bash" && event.isError) {\n      return { isError: true }; // preserve the failed observation\n    }\n  });\n}', urls.extensions, [4, 5, 6]),
  edit: wire('Pi edit tool · illustrative arguments', '{\n  "path": "help.md",\n  "oldText": "# Welcomme",\n  "newText": "# Welcome"\n}', urls.pi, [2, 3, 4]),
  session: wire('session.jsonl · illustrative message entries', '{"type":"message","id":"a0000001","parentId":null,"timestamp":"2026-09-07T09:00:00.000Z","message":{"role":"user","content":"Fix the workshop typo."}}\n{"type":"message","id":"a0000002","parentId":"a0000001","timestamp":"2026-09-07T09:00:01.000Z","message":{"role":"toolResult","toolCallId":"call_demo","toolName":"bash","content":[{"type":"text","text":"PASS"}],"isError":false}}', urls.sessions, [1, 2]),
  resume: api('Pi terminal · session commands', 'sh', 'pi --continue\n# Or inspect saved sessions:\npi --resume\n# Inside Pi, inspect branches:\n/tree', urls.pi, [1, 3, 5]),
  tree: api('.pi/extensions/session-observer.ts · optional extension', 'typescript', 'import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";\n\nexport default function (pi: ExtensionAPI) {\n  pi.on("session_before_tree", () => {\n    // May return { cancel: true } to stop this navigation.\n  });\n  pi.on("session_tree", (event) => {\n    // event.oldLeafId and event.newLeafId identify the branch move.\n  });\n}', urls.extensions, [4, 7, 8]),
};

const codex = {
  command: api('terminal · scoped Codex session', 'sh', 'codex --sandbox workspace-write --ask-for-approval on-request\n# Inside the session, inspect active permissions:\n/permissions', urls.sandbox, [1, 3]),
  config: api('config.toml · illustrative documented settings', 'toml', 'sandbox_mode = "workspace-write"\napproval_policy = "on-request"\n\n[sandbox_workspace_write]\nnetwork_access = false', urls.sandbox, [1, 2, 5]),
  chain: pseudo('AGENTS.md discovery · documented behavior', '~/.codex/AGENTS.override.md OR AGENTS.md\n  ↓\nrepository root: AGENTS.override.md OR AGENTS.md\n  ↓\ncurrent-directory chain: closest guidance is appended later\n\nGuidance enters the prompt; it does not create a sandbox.', urls.agents, [1, 3, 5, 7]),
  runtime: pseudo('Codex loop · architectural cutaway', 'user task + instruction chain + observations\n  → model proposes next action\n  → harness checks applicable permissions\n  → permitted tool executes in configured environment\n  → observation returns to the model\n  → outcome still needs independent verification', urls.sandbox, [2, 3, 4]),
  proposal: pseudo('Codex tool proposal · no private protocol claimed', 'Proposed action: edit help.md\nOld heading: # Welcomme\nNew heading: # Welcome\nPreserve: [FAQ](./faq.md)\n\nThis is a conceptual proposal, not a claimed Codex wire schema.', urls.codex, [1, 2, 3, 4]),
  boundary: pseudo('Configured sandbox · teaching decision', 'Workspace: extracted fictional project\nAllowed writes: configured writable workspace roots\nNetwork: disabled in this example\nOutside-scope action: requires the configured approval path\n\nA prompt saying "do not export" is not OS isolation.', urls.sandbox, [2, 3, 4]),
  resume: api('terminal · return to saved Codex chat', 'sh', 'codex resume\n# Select the intended saved chat in the picker.\n# Then ask Codex to inspect the current file and rerun:\nnode verify.mjs', urls.codex, [1, 4]),
};

const claude = {
  command: api('terminal · Claude Code', 'sh', 'claude\n# Inspect project guidance in the session:\n/memory', urls.claude, [1, 3]),
  hooks: api('.claude/settings.json · illustrative hook config', 'json', '{\n  "hooks": {\n    "PreToolUse": [{\n      "matcher": "Edit|Write",\n      "hooks": [{ "type": "command",\n        "command": "node \\"$CLAUDE_PROJECT_DIR\\"/check-scope.mjs" }]\n    }]\n  }\n}', urls.claudeHooks, [3, 4, 6]),
  deny: wire('PreToolUse · illustrative hook output', '{\n  "hookSpecificOutput": {\n    "hookEventName": "PreToolUse",\n    "permissionDecision": "deny",\n    "permissionDecisionReason": "The proposed write is outside this task."\n  }\n}', urls.claudeHooks, [3, 4, 5]),
  permissions: api('.claude/settings.json · documented permission syntax', 'json', '{\n  "permissions": {\n    "deny": ["Read(./.env)", "Edit(./faq.md)"]\n  }\n}', urls.claudePermissions, [2, 3]),
  tool: wire('PreToolUse · illustrative event input', '{\n  "hook_event_name": "PreToolUse",\n  "tool_name": "Edit",\n  "tool_input": {\n    "file_path": "/workshop/help.md",\n    "old_string": "# Welcomme",\n    "new_string": "# Welcome"\n  }\n}', urls.claudeHooks, [2, 3, 5, 6, 7]),
  post: api('.claude/settings.json · illustrative verification hook', 'json', '{\n  "hooks": {\n    "PostToolUse": [{\n      "matcher": "Edit|Write",\n      "hooks": [{ "type": "command",\n        "command": "node \\"$CLAUDE_PROJECT_DIR\\"/verify.mjs" }]\n    }]\n  }\n}', urls.claudeHooks, [3, 4, 6]),
  stop: wire('Stop · illustrative corrective hook output', '{\n  "decision": "block",\n  "reason": "The FAQ link check failed. Correct the file and run verify.mjs."\n}', urls.claudeHooks, [2, 3]),
  resume: api('terminal · resume Claude Code', 'sh', 'claude --resume\n# Choose the intended saved session.\n# Inspect actual files after resuming; the chat is not the filesystem.\nnode verify.mjs', urls.claudeCli, [1, 3, 4]),
  startup: wire('SessionStart · illustrative resume event', '{\n  "hook_event_name": "SessionStart",\n  "source": "resume",\n  "session_id": "fictional-session",\n  "cwd": "/workshop"\n}', urls.claudeHooks, [2, 3, 5]),
};

const factory = {
  command: api('terminal · interactive Factory Droid', 'sh', 'droid\n# Inspect lifecycle configuration in the session:\n/hooks', urls.factoryCli, [1, 3]),
  hook: api('.factory/hooks.json · illustrative hook config', 'json', '{\n  "PreToolUse": [{\n    "matcher": "Edit|Create|ApplyPatch",\n    "hooks": [{ "type": "command",\n      "command": "node \\"$FACTORY_PROJECT_DIR\\"/check-scope.mjs"\n    }]\n  }]\n}', urls.factoryHooks, [2, 3, 5]),
  lifecycle: pseudo('Droid lifecycle · documented event names', 'UserPromptSubmit → task enters the session\nPreToolUse → tool dispatch can be blocked\nPostToolUse → tool has already run\nStop → completion can receive corrective feedback\nPreCompact → prepare compaction\nSessionStart → startup / resume / clear / compact', urls.factoryHooks, [2, 3, 4]),
  deny: wire('PreToolUse · illustrative Droid hook output', '{\n  "hookSpecificOutput": {\n    "hookEventName": "PreToolUse",\n    "permissionDecision": "deny",\n    "permissionDecisionReason": "Folder export is outside this task."\n  }\n}', urls.factoryHooks, [3, 4, 5]),
  input: wire('Droid Execute · illustrative hook input', '{\n  "hook_event_name": "PreToolUse",\n  "permission_mode": "off",\n  "tool_name": "Execute",\n  "tool_input": { "command": "node verify.mjs" },\n  "cwd": "/workshop"\n}', urls.factoryHooks, [2, 4, 5]),
  post: api('.factory/hooks.json · illustrative after-edit check', 'json', '{\n  "PostToolUse": [{\n    "matcher": "Edit|Create|ApplyPatch",\n    "hooks": [{ "type": "command",\n      "command": "node \\"$FACTORY_PROJECT_DIR\\"/verify.mjs"\n    }]\n  }]\n}', urls.factoryHooks, [2, 3, 5]),
  stop: wire('Stop · illustrative corrective Droid output', '{\n  "decision": "block",\n  "reason": "The artifact still fails verify.mjs; correct forward."\n}', urls.factoryHooks, [2, 3]),
  resume: api('terminal · resume a Droid session', 'sh', 'droid --resume\n# --resume selects a previous interactive session.\n# Reconcile files and verification after continuation.\nnode verify.mjs', urls.factoryCli, [1, 3, 4]),
  startup: wire('SessionStart · illustrative Droid resume input', '{\n  "hook_event_name": "SessionStart",\n  "source": "resume",\n  "session_id": "fictional-session",\n  "cwd": "/workshop"\n}', urls.factoryHooks, [2, 3, 5]),
};

const deepseek = {
  entry: api('Pi terminal · select a DeepSeek model', 'sh', 'pi\n# Configure your provider through the normal account flow.\n/model\n# Select an available DeepSeek model. No credential belongs in this page.', urls.pi, [1, 3, 4]),
  request: wire('DeepSeek request · abbreviated teaching payload', '{\n  "messages": [{\n    "role": "user",\n    "content": "Fix Welcomme in help.md; preserve ./faq.md."\n  }],\n  "tools": [{ "type": "function", "function": {\n    "name": "edit",\n    "parameters": { "type": "object", "properties": {\n      "path": { "type": "string" },\n      "oldText": { "type": "string" },\n      "newText": { "type": "string" }\n    }, "required": ["path", "oldText", "newText"] }\n  }}]\n}', urls.deepseek, [4, 6, 7, 12]),
  response: wire('DeepSeek response · illustrative tool-call fragment', '{\n  "role": "assistant",\n  "tool_calls": [{\n    "id": "call_demo", "type": "function",\n    "function": {\n      "name": "edit",\n      "arguments": "{\\"path\\":\\"help.md\\",\\"oldText\\":\\"# Welcomme\\",\\"newText\\":\\"# Welcome\\"}"\n    }\n  }]\n}', urls.deepseek, [3, 4, 6, 7]),
  result: wire('DeepSeek continuation · illustrative tool result', '{\n  "role": "tool",\n  "tool_call_id": "call_demo",\n  "content": "The edit tool completed. Independent verification is still required."\n}', urls.deepseek, [2, 3, 4]),
  host: pseudo('Pi host dispatch · conceptual responsibilities', 'Receive provider tool-call proposal\nValidate the tool name and arguments\nApply installed extensions and environment restrictions\nExecute only the permitted local operation\nAssociate its result with the original tool-call ID\nReturn the observation to the provider', urls.deepseek, [2, 3, 4, 5]),
  session: pseudo('Pi session vs. tool operation · distinct identities', 'Provider tool_call_id: correlates a result with a request\nPi session entry id / parentId: connects conversation branches\nApplication operation key: deduplicates a business effect, IF implemented\n\nNone of these identifiers automatically substitutes for the others.', urls.sessions, [1, 2, 3, 5]),
};

type Item = [label: string, asset: StageAsset, detail: string, snippet: StageCode];
type Story = { title: string; nodes: Item[]; beats: [string, string][]; blocked?: number };
const item = (label: string, asset: StageAsset, detail: string, snippet: StageCode): Item => [label, asset, detail, snippet];
const target = () => item('help.md', 'editor', 'A real file in the downloadable starter kit. Inspect the typo and the relative FAQ link.', original);
const output = () => item('One-line document diff', 'diff-board', 'The expected change affects the heading only. This visual diff is authored from the real fixture.', diff);
const check = () => item('Independent verifier', 'test-rig', 'The downloaded Node script checks complete expected files. A successful edit tool alone does not satisfy it.', verifier);

const stories: Record<PublicProvider, Record<StageTopic, Story>> = {
  pi: {
    contract: { title: 'Build the Pi workbench around one contract', nodes: [target(), item('AGENTS.md', 'context-stack', 'Pi discovers project guidance; the file constrains the requested result, not the operating system.', instructions()), item('Three Pi package layers', 'model-chip', 'The model API, agent runtime and coding interface are separate packages. This is the current package scope, not a dependency to install here.', pi.packages), item('before_agent_start extension', 'extension-rack', 'An optional extension can append per-turn context before the agent loop. This sample does not install an extension.', pi.before), output(), check()], beats: [['Read the target', 'The file is small enough to inspect completely; keep the FAQ link visible while defining the change.'], ['Load the project agreement', 'AGENTS.md names the allowed edit and required check. Pi’s prompt can use this contract; a prompt is not an execution boundary.'], ['Separate the Pi layers', 'pi-ai speaks to models; pi-agent-core runs the agent; pi-coding-agent supplies the coding interface, sessions and extension surface.'], ['Watch the optional extension seam', 'before_agent_start can modify the per-turn prompt. This is an extension you author, not an invisible built-in governance engine.'], ['Close on evidence', 'The expected diff and the independent verifier jointly make done observable. A final assistant sentence alone does not.']] },
    context: { title: 'Pack context at Pi’s extension seam', nodes: [target(), item('Project rules', 'context-stack', 'Keep the file and its preservation rule together; unrelated history is not necessary for this task.', instructions()), item('Model API adapter', 'api-gateway', 'Pi’s model API layer adapts provider requests; changing a model does not replace project guidance or extension code.', pi.packages), item('before_agent_start', 'extension-rack', 'The documented event exposes the prompt and can append a per-turn system prompt contribution.', pi.before), item('Exact edit arguments', 'tool-workbench', 'Selected context should be sufficient to form this bounded edit; the outside world has not changed yet.', pi.edit), check()], beats: [['Locate the relevant text', 'Read the actual heading and link before selecting evidence.'], ['Carry the rule with the file', 'The target document says what exists; AGENTS.md says what the task should preserve.'], ['Keep adapter and prompt distinct', 'The provider adapter serializes model requests. Project context and extension changes are supplied by the coding harness around it.'], ['Inspect injected context', 'The highlighted before_agent_start lines append one explicit constraint. Review extension contributions rather than assuming they are harmless.'], ['Test whether the briefing was enough', 'The resulting edit must still pass the same verifier. A shorter briefing is useful only if it preserves the necessary facts and rules.']] },
    permissions: { title: 'See Pi’s optional policy extension before tools', nodes: [item('Requested scope', 'editor', 'The intended task is a local typo correction, not a folder export.', task), item('Active tool surface', 'tool-workbench', 'Default coding tools and installed extensions define available operations. The export_folder name below is a fictional custom tool.', pseudo('Pi tools · documented defaults + teaching custom tool', 'Default tools: read, write, edit, bash\nTeaching-only custom proposal: export_folder\nInstalled extensions may add or restrict tools.\nPi core has no permission popups.', urls.pi, [1, 2, 4])), item('Proposed tool call', 'model-chip', 'A tool proposal has no external effect until the host dispatches it.', wire('tool_call · teaching custom event', '{ "toolName": "export_folder", "toolCallId": "demo_export", "input": {} }', urls.extensions)), item('tool_call extension', 'extension-rack', 'The shown optional extension explicitly blocks this fictional tool name. It is not a complete sandbox or a path-policy implementation.', pi.gate), output(), check()], blocked: 3, beats: [['Name the legitimate task', 'Authority starts with the authorized user task and configured environment. Outside source text cannot expand it.'], ['Inspect the tool inventory', 'Pi does not ship permission popups. An extension can add checks; OS or container isolation is a separate deployment decision.'], ['Catch the proposal', 'The model requests the teaching custom export_folder tool. The request itself exports nothing.'], ['Block at tool_call', 'Returning block: true from the installed extension prevents this tool execution. A native shell tool needs its own appropriate controls; matching one custom name is not general isolation.'], ['Continue with the authorized edit', 'Containment and task completion are different. The heading repair still requires its allowed edit and passing file check.']] },
    verification: { title: 'Inspect Pi tool results without believing them blindly', nodes: [target(), item('Edit arguments', 'tool-workbench', 'The model proposes a narrow text replacement; a successful tool response is still only an observation.', pi.edit), item('Agent runtime', 'model-chip', 'The runtime receives tool observations and lets the model continue; it does not make this fixture’s acceptance contract disappear.', pi.packages), item('tool_result extension', 'extension-rack', 'An optional event handler can inspect or modify tool results. This example preserves an error instead of turning it into success.', pi.result), output(), check()], beats: [['Identify the required invariant', 'The FAQ link is part of the contract even if the visible typo looks trivial.'], ['Inspect the proposed edit', 'Exact old/new text keeps the change narrow, but later errors or unexpected effects can still occur.'], ['Understand the return path', 'A result returns through Pi’s runtime to the model. It reports tool activity; it is not an independent acceptance decision.'], ['Preserve failure evidence', 'tool_result can modify observations. Do not sanitize away isError and accidentally teach the model that a failed action succeeded.'], ['Run the real verifier', 'The downloaded script checks both complete files. Inspect the diff and command result before accepting completion.']] },
    recovery: { title: 'Navigate Pi’s session tree, then inspect the files', nodes: [item('Saved Pi session', 'terminal', 'Continue or select the intended session. These commands restore conversation context, not a prior filesystem snapshot.', pi.resume), item('JSONL parent links', 'session-tree', 'Session entries link through id and parentId. The payload is an abbreviated fictional example of the documented format.', pi.session), item('Runtime and session state', 'model-chip', 'Conversation state is one part of the coding harness. The model does not independently own the filesystem or an operation ledger.', pi.packages), item('Tree navigation events', 'extension-rack', 'Extensions can observe or cancel tree navigation through documented session events.', pi.tree), output(), check()], beats: [['Choose the saved session', 'Resume the task you actually intend to continue; a neighboring conversation may have a different contract.'], ['Inspect the branch relationship', 'id and parentId describe the session tree. Changing its active leaf changes conversational context.'], ['Separate conversation from effects', 'A restored chat does not undo an edit, and a replayed message does not prove a business operation is idempotent.'], ['Observe the tree event', 'session_before_tree can cancel navigation; session_tree reports the leaf change. These hooks do not supply an automatic exactly-once write guarantee.'], ['Revalidate the present artifact', 'Read help.md and rerun verify.mjs before doing more work. If an external effect is ambiguous, reconcile its own operation identity first.']] },
  },
  codex: {
    contract: { title: 'Give Codex a contract inside a configured workspace', nodes: [target(), item('AGENTS.md instruction chain', 'context-stack', 'Codex loads guidance from global and project scopes. The workshop file names the acceptance criteria.', instructions()), item('Codex CLI', 'terminal', 'The shown invocation selects a writable workspace and ordinary on-request approval behavior.', codex.command), item('Execution sandbox', 'sandbox', 'Runtime configuration governs execution separately from task prose.', codex.config), output(), check()], beats: [['Inspect the one-file task', 'The typo and FAQ link establish the starting state.'], ['Read the acceptance rules', 'AGENTS.md defines the permitted correction and evidence. Codex’s discovered instruction chain may also contain broader project rules.'], ['Launch in the intended workspace', 'The directory and active settings determine what environment the agent can access; the task text should match that scope.'], ['Inspect the configured boundary', 'Workspace-write and network settings are runtime controls. They are distinct from the instruction to preserve a link.'], ['Require artifact evidence', 'Only the expected diff plus the independent file check satisfies this small contract.']] },
    context: { title: 'Trace the Codex instruction chain into a tool proposal', nodes: [target(), item('Instruction discovery', 'context-stack', 'Codex discovers one applicable guidance file per directory and combines the chain; closer project guidance is appended later.', codex.chain), item('Codex action loop', 'model-chip', 'This cutaway is conceptual, not a published internal request schema.', codex.runtime), item('Configured workspace', 'sandbox', 'Readable context and permitted effects are related but different concerns.', codex.boundary), item('Bounded edit proposal', 'tool-workbench', 'The proposal preserves the link because the selected context includes the invariant.', codex.proposal), check()], beats: [['Read the actual file', 'Do not reconstruct the heading from a vague description when the target is available.'], ['Resolve applicable guidance', 'Global guidance and the path from repository root to working directory contribute to Codex’s instruction chain.'], ['Observe context becoming a proposal', 'The model uses task instructions and observations to propose the next action. This is a conceptual diagram, not access to model reasoning.'], ['Keep permissions separate', 'Including a file in the briefing is not permission to publish its contents. Runtime configuration still controls tool execution.'], ['Check the result against the original facts', 'The verifier catches unintended changes even when the briefing looked complete.']] },
    permissions: { title: 'Cut through Codex’s sandbox and approval boundary', nodes: [item('Authorized task', 'editor', 'The mission needs a local correction and check, not network export.', task), item('Permission configuration', 'context-stack', 'These are documented settings for a teaching profile; they do not alter this running app.', codex.config), item('Action proposal', 'model-chip', 'The model proposes an operation; the surrounding harness evaluates its permission requirements.', codex.runtime), item('Workspace and network boundary', 'sandbox', 'This example keeps network disabled and writes scoped to configured workspace roots.', codex.boundary), output(), check()], blocked: 3, beats: [['Separate intent from authority', 'The task describes a correction; it does not request wider filesystem or network access.'], ['Read the effective settings', 'sandbox_mode and approval_policy answer different questions: execution isolation and handling of permission requests.'], ['Pause at the proposed action', 'A proposal is not yet an effect. The diagram does not imply that model text enforces the sandbox.'], ['Respect the configured boundary', 'An out-of-scope operation cannot simply inherit permission from a source document. Follow the actual configured approval path without assuming it was granted.'], ['Verify the allowed work', 'A permitted local edit still needs a passing outcome check. Permission is not correctness.']] },
    verification: { title: 'Make Codex’s completion claim meet the file check', nodes: [target(), item('Project acceptance rule', 'context-stack', 'The rule says how to prove completion, not just how to describe it.', instructions()), item('Codex proposal loop', 'model-chip', 'The assistant can propose edits and checks; this diagram exposes their roles without claiming private implementation details.', codex.runtime), item('Permitted execution', 'sandbox', 'The verifier must run within the configured environment and permissions.', codex.config), output(), check()], beats: [['Keep the original invariant visible', 'Fixing the heading while breaking the FAQ link is still a failed task.'], ['Locate the check in AGENTS.md', 'A discoverable check instruction helps the agent know which evidence to obtain.'], ['Distinguish a claim from a result', 'The final assistant message may summarize evidence; it cannot replace the evidence.'], ['Run the check in the workspace', 'The runtime executes the requested check under the active permissions. An exit code is an observation you can inspect.'], ['Compare complete files', 'The fixture verifier rejects unrelated changes. Use the actual diff and check outcome to judge completion.']] },
    recovery: { title: 'Resume Codex without confusing chat state with file state', nodes: [item('Saved Codex chat', 'terminal', 'The resume picker selects a previous local conversation.', codex.resume), item('Current project guidance', 'context-stack', 'Read applicable current guidance after returning; the repository may have changed.', codex.chain), item('Resumed action loop', 'model-chip', 'A resumed loop needs fresh observations when the world may have changed.', codex.runtime), item('Current permissions', 'sandbox', 'Recheck the active execution boundary rather than assuming a previous approval grants everything.', codex.config), output(), check()], beats: [['Resume the intended chat', 'The session command restores context for the work you select.'], ['Check current instructions', 'A saved conversation can outlive changes to project conventions or files.'], ['Treat the saved plan as a hypothesis', 'The prior plan records intent; inspect whether its effects actually exist.'], ['Keep the current runtime boundary', 'Continuation does not justify bypassing sandbox or approval settings.'], ['Reconcile before repeating', 'If the typo is already fixed and the verifier passes, do not create another action merely because a receipt was lost.']] },
  },
  claude: {
    contract: { title: 'Connect CLAUDE.md to Claude Code’s hook rail', nodes: [target(), item('CLAUDE.md', 'context-stack', 'Claude Code’s project memory surface contains the exact workshop contract.', instructions('CLAUDE.md')), item('Claude Code session', 'terminal', 'Use /memory to inspect loaded guidance rather than assuming it was discovered.', claude.command), item('PreToolUse seam', 'permission-gate', 'The example hook config names a script you would need to implement; it is not included in the starter kit.', claude.hooks), output(), check()], beats: [['Read the task document', 'The file defines the concrete before state.'], ['Inspect CLAUDE.md', 'The project memory names the typo, preserved link and check command.'], ['Confirm loaded memory', 'The /memory surface helps you understand which instructions entered this session.'], ['Separate guidance from hooks', 'CLAUDE.md influences behavior. A PreToolUse hook is executable host logic at a defined lifecycle point.'], ['Check the artifact', 'Neither memory loading nor hook execution alone proves the resulting document meets the contract.']] },
    context: { title: 'Keep Claude Code memory and permission rules distinct', nodes: [target(), item('CLAUDE.md briefing', 'context-stack', 'The actual project instructions carry the one-file scope and link invariant.', instructions('CLAUDE.md')), item('Loaded memory', 'terminal', 'Inspect project context through the documented /memory command.', claude.command), item('Permission settings', 'permission-gate', 'Permission rules govern access; they are not prose in CLAUDE.md.', claude.permissions), item('Proposed Edit input', 'tool-workbench', 'The illustrative event shows typed edit parameters after Claude has proposed a tool operation.', claude.tool), check()], beats: [['Start with a concrete source', 'The document is evidence about the current file, not a source of new authority.'], ['Load the relevant memory', 'The contract belongs in concise project guidance that the session actually reads.'], ['Inspect what was loaded', 'Do not assume that a file with a familiar name is active in every session or scope.'], ['Check the access layer separately', 'Read deny rules also matter for direct file references; a PreToolUse hook does not fire merely because an @ reference enters the prompt.'], ['Verify the transfer into an edit', 'The proposed replacement and the independent check show whether the useful context survived into the result.']] },
    permissions: { title: 'Stop a Claude Code proposal at PreToolUse', nodes: [item('Task scope', 'editor', 'The task authorizes the typo correction; it does not authorize arbitrary writes.', task), item('Hook configuration', 'extension-rack', 'The matcher selects Edit and Write events. A real scope script must understand paths and input schemas.', claude.hooks), item('Outside-scope Edit event', 'model-chip', 'The documented event carries tool_name and tool_input; this proposal targets a fictional path outside the workshop.', { ...claude.tool, text: claude.tool.text.replace('/workshop/help.md', '/outside/unrelated.md') }), item('PreToolUse denial', 'permission-gate', 'A deny response blocks execution. The sample output is illustrative, not a currently installed rule.', claude.deny), output(), check()], blocked: 3, beats: [['Identify the allowed change', 'Scope is a task property that must be interpreted by the surrounding system.'], ['Match a specific lifecycle event', 'PreToolUse runs before tool processing. PostToolUse is too late to prevent the original write.'], ['Inspect the proposed parameters', 'Look at the absolute file path and exact replacement, not just the human description of the tool.'], ['Observe a denying hook decision', 'permissionDecision: deny stops the proposal before its effect. Hook allowances do not erase applicable deny rules.'], ['Return to the legitimate edit', 'A correctly denied unrelated action leaves the typo task pending. Finish with the allowed edit and check.']] },
    verification: { title: 'Use Claude Code’s after-tool seam for feedback', nodes: [target(), item('PostToolUse configuration', 'extension-rack', 'This illustrative config invokes the real verifier after Edit or Write. It is displayed, not installed.', claude.post), item('Tool execution', 'tool-workbench', 'The edit event describes the requested replacement; inspect the result separately.', claude.tool), item('Stop feedback', 'permission-gate', 'An optional Stop hook can request correction. It must handle stop_hook_active and avoid an endless blocking loop.', claude.stop), output(), check()], beats: [['Keep the FAQ contract', 'The check is about the complete artifact, not whether a tool returned successfully.'], ['Place after-edit feedback', 'PostToolUse occurs after execution. Its feedback can expose a bad result but cannot retroactively prevent the edit.'], ['Inspect what actually changed', 'Read the artifact or diff instead of trusting only tool parameters.'], ['Avoid a premature finish', 'A Stop hook can return a corrective reason. This teaching output assumes a verifier detected failure; no such hook is installed here.'], ['Accept evidence, not the hook itself', 'A passing verifier and expected document close the loop. The existence of a Stop hook is not proof of correctness.']] },
    recovery: { title: 'Resume Claude Code and re-read the environment', nodes: [item('Resume picker', 'terminal', 'Select the intended conversation; a resume does not restore past file contents.', claude.resume), item('Project memory', 'context-stack', 'CLAUDE.md supplies the task convention, while saved messages supply history.', instructions('CLAUDE.md')), item('SessionStart resume event', 'queue', 'The source field distinguishes resume from a fresh startup.', claude.startup), item('Permission revalidation', 'permission-gate', 'Current permissions still govern the next tool call.', claude.permissions), output(), check()], beats: [['Choose the conversation', 'Restore the intended session with the documented resume flow.'], ['Recover the contract', 'Use the task and project guidance to understand what success was supposed to mean.'], ['Observe the lifecycle boundary', 'A SessionStart event with source resume is a hook opportunity, not a durable business-operation guarantee.'], ['Keep the current access rules', 'A resumed message history does not justify wider write permissions.'], ['Check the present state', 'Read help.md and run the check. Reconcile any ambiguous external operation through its own state and identity before retrying.']] },
  },
  factory: {
    contract: { title: 'Build Droid’s gated pipeline from the project agreement', nodes: [target(), item('Droid AGENTS.md', 'context-stack', 'Droid reads project instructions that name scope and verification commands.', instructions()), item('Interactive Droid', 'terminal', 'The interactive CLI exposes the same runtime through its terminal surface.', factory.command), item('PreToolUse hook stage', 'permission-gate', 'Factory uses a top-level event map in .factory/hooks.json; the example scope script is not supplied.', factory.hook), output(), check()], beats: [['Inspect the target', 'The requested change is a specific typo correction.'], ['Put evidence in AGENTS.md', 'Droid’s project briefing includes the required check, so done has a concrete definition.'], ['Inspect the active runtime', 'The /hooks manager exposes lifecycle configuration. This page describes that surface without invoking it.'], ['Read the gate configuration', 'The event map differs from Claude Code’s settings wrapper. Tool names and matcher spelling matter.'], ['Verify the final file', 'A gated pipeline still needs acceptance evidence; authorization does not guarantee the edit is right.']] },
    context: { title: 'Follow Droid context through lifecycle stages', nodes: [target(), item('Project briefing', 'context-stack', 'AGENTS.md supplies concise commands, boundaries and conventions.', instructions()), item('Lifecycle event rail', 'queue', 'The documented events separate prompt entry, tool execution and completion.', factory.lifecycle), item('Session context hook', 'extension-rack', 'SessionStart can add context on startup or resume; this is an event illustration.', factory.startup), item('Execute proposal', 'tool-workbench', 'The tool payload uses Factory’s Execute name and command input.', factory.input), check()], beats: [['Choose relevant source content', 'The target file and its rules are useful; unrelated archives dilute the briefing.'], ['Load the project agreement', 'A discovered AGENTS.md file carries instructions, not operating-system isolation.'], ['Distinguish lifecycle moments', 'UserPromptSubmit, PreToolUse and PostToolUse are different opportunities; a check placed after a tool cannot stop its original effect.'], ['Inspect added session context', 'SessionStart can append context. Review what enters the session and preserve source authority.'], ['Observe the proposed check', 'The Execute proposal names node verify.mjs; its eventual result must be inspected to establish success.']] },
    permissions: { title: 'Stop a Droid action before dispatch', nodes: [item('Authorized scope', 'editor', 'One fictional file correction is authorized; folder export is not.', task), item('.factory/hooks.json', 'extension-rack', 'This Execute matcher reaches the fictional shell export proposal. Its named scope-check script is not supplied.', { ...factory.hook, text: factory.hook.text.replace('Edit|Create|ApplyPatch', 'Execute') }), item('Outside-scope Execute proposal', 'queue', 'The fictional export-fixture.mjs script is not supplied or executed; it makes the proposed unrelated action explicit.', { ...factory.input, text: factory.input.text.replace('node verify.mjs', 'node export-fixture.mjs') }), item('PreToolUse gate', 'permission-gate', 'The illustrative deny output prevents this outside-scope proposal from executing.', factory.deny), output(), check()], blocked: 3, beats: [['Name the intended operation', 'The user’s correction task has a narrow boundary.'], ['Inspect the concrete matcher', 'Edit, Create and ApplyPatch are Factory tool names. A mismatch can leave your intended hook unused.'], ['Pause at dispatch', 'PreToolUse receives tool_name and tool_input before execution. The pipeline has not yet changed the file.'], ['Deny the unrelated operation', 'A denying hook result blocks the tool. The diagram is not a live approval grant or proof that this sample script is installed.'], ['Complete the permitted work', 'A denied export is successful containment; it does not repair the typo. Run the authorized edit and verify its artifact.']] },
    verification: { title: 'Make Droid’s post-tool evidence govern completion', nodes: [target(), item('After-edit check hook', 'extension-rack', 'PostToolUse can run the workshop verifier after file-changing tools.', factory.post), item('Execute verification', 'tool-workbench', 'Factory calls its shell tool Execute; the command and result remain inspectable.', factory.input), item('Stop feedback gate', 'permission-gate', 'A Stop hook may send corrective feedback when the artifact fails; the example does not install one.', factory.stop), output(), check()], beats: [['Retain the full invariant', 'The unchanged FAQ target is part of the outcome.'], ['Attach feedback at the right stage', 'PostToolUse runs after the tool. Its failure can request a forward correction, not undo the earlier action.'], ['Observe the actual verification command', 'The Execute tool must return the check’s outcome; a model’s successful narration is insufficient.'], ['Refuse premature completion', 'A Stop hook can request more work with decision block and a reason. Ensure any real hook can terminate rather than loop indefinitely.'], ['Inspect final evidence', 'The diff and exact-file verifier establish this fixture’s acceptance criteria. They do not certify the wider runtime.']] },
    recovery: { title: 'Resume Droid through its session pipeline', nodes: [item('Droid resume', 'terminal', 'The interactive --resume flag returns to a previous session. It is distinct from exec reasoning-effort shorthand.', factory.resume), item('Project agreement', 'context-stack', 'The current AGENTS.md still defines scope and checks.', instructions()), item('SessionStart source', 'queue', 'The documented resume event gives hooks a lifecycle point to restore useful context.', factory.startup), item('Current hook policy', 'permission-gate', 'Resuming does not bypass the applicable configured hooks or permissions.', factory.hook), output(), check()], beats: [['Select the saved session', 'Use the documented interactive resume flow; choose the intended task.'], ['Recover the acceptance contract', 'Old conversation text should be read alongside the project’s current instructions.'], ['Observe the resumed pipeline', 'SessionStart with source resume is an opportunity for context loading, not proof of external operation state.'], ['Reapply current boundaries', 'The next action must still pass the runtime’s applicable checks.'], ['Reconcile before repeating', 'Inspect the existing artifact and run verify.mjs. A timeout does not establish that the original edit failed.']] },
  },
  deepseek: {
    contract: { title: 'Follow a DeepSeek proposal across Pi’s wire boundary', nodes: [item('Pi host + chosen model', 'terminal', 'Pi hosts this example. DeepSeek supplies the model; the browser does not call either service.', deepseek.entry), item('Task and tool schema', 'context-stack', 'The abbreviated payload illustrates user context and a function definition; production requests need the selected model and normal provider configuration.', deepseek.request), item('DeepSeek tool proposal', 'api-gateway', 'The provider returns a tool call with string-encoded arguments. It does not edit the local file.', deepseek.response), item('Pi local dispatch', 'tool-workbench', 'The host owns validation, configured controls and actual execution.', deepseek.host), output(), check()], beats: [['Choose the host and model', 'The Pi executable runs locally; the selected DeepSeek model supplies proposals through its API.'], ['Serialize the acceptance context', 'The request must carry the task and available tool schema. A schema alone does not express all authorization policy.'], ['Inspect the provider response', 'tool_calls contains an operation proposal and arguments; no local effect has occurred in the model service.'], ['Dispatch through the host', 'Pi performs the local operation under its installed extensions and execution environment.'], ['Judge the actual artifact', 'The same verifier applies regardless of which model proposed the correction.']] },
    context: { title: 'Cut open DeepSeek’s request and continuation', nodes: [target(), item('Serialized user context', 'context-stack', 'The visible request is an authored abbreviated wire illustration using documented fields.', deepseek.request), item('Provider response', 'api-gateway', 'The model selects a tool and serializes its arguments as a JSON string.', deepseek.response), item('Pi adapter and dispatch', 'tool-workbench', 'The host must validate and execute permitted calls before it can return an observation.', deepseek.host), item('Tool-result continuation', 'api-gateway', 'The return message associates the observation with the original tool call.', deepseek.result), check()], beats: [['Select the necessary source', 'The typo and link rule are facts the model needs to form a useful proposal.'], ['Inspect the outgoing payload', 'messages carries context and tools describes callable shapes. The displayed payload omits credentials and model selection intentionally.'], ['Distinguish schema from behavior', 'A well-formed edit request can still be semantically wrong. JSON validity is not task correctness.'], ['Preserve the observation handoff', 'The host executes the permitted operation and returns the result against the original call ID.'], ['Verify outside the model response', 'Check the actual files after the tool result. More fluent continuation text cannot repair a broken invariant.']] },
    permissions: { title: 'Keep DeepSeek’s proposed call outside the local boundary', nodes: [item('Authorized task', 'editor', 'The user requested a local edit. Model output cannot confer extra authority.', task), item('Custom export tool schema', 'context-stack', 'This fictional extension-provided tool is declared only to demonstrate denial. It is not a built-in Pi tool or a permission grant.', wire('DeepSeek request · fictional custom tool', '{\n  "tools": [{ "type": "function", "function": {\n    "name": "export_folder",\n    "parameters": { "type": "object", "properties": {} }\n  }}]\n}', urls.deepseek, [2, 3, 4])), item('Custom export proposal', 'api-gateway', 'The response requests the fictional tool; the installed host extension below would block that tool name.', wire('DeepSeek response · fictional custom call', '{\n  "role": "assistant",\n  "tool_calls": [{ "id": "demo_export", "type": "function",\n    "function": { "name": "export_folder", "arguments": "{}" }\n  }]\n}', urls.deepseek, [3, 4])), item('Optional Pi tool_call gate', 'extension-rack', 'The example Pi extension blocks a fictional custom export tool. Pi has no built-in permission popups and this is not a complete sandbox.', pi.gate), item('Local dispatcher', 'tool-workbench', 'The actual host environment must enforce the intended access boundary before effects.', deepseek.host), check()], blocked: 3, beats: [['Name what is authorized', 'The correction contract stays the same when the provider changes.'], ['Read the tool definition correctly', 'Function schema validation concerns argument shape; it does not authorize folder export or unrelated writes.'], ['Treat output as a proposal', 'DeepSeek’s response reaches the host without directly modifying files.'], ['Enforce at the host seam', 'An installed Pi extension can block tool_call before execution. Broader isolation requires appropriate host and OS controls.'], ['Keep the legitimate task pending', 'If an unrelated proposal is denied, continue only through a permitted operation and verify the result.']] },
    verification: { title: 'Compare DeepSeek’s returned observation with real evidence', nodes: [target(), item('Proposed edit payload', 'api-gateway', 'This response fragment describes a requested tool invocation, not its outcome.', deepseek.response), item('Pi local execution', 'tool-workbench', 'The host performs the actual edit and observes its result.', deepseek.host), item('Tool result to provider', 'api-gateway', 'A role tool message correlates the observation with tool_call_id. It may describe tool success without proving the full contract.', deepseek.result), output(), check()], beats: [['Keep the expected document visible', 'The FAQ link must survive the change.'], ['Inspect what the model requested', 'Arguments propose a narrow edit; they are not evidence that the edit happened correctly.'], ['Find where execution occurs', 'The local Pi tool implementation performs the operation, not the DeepSeek model service.'], ['Read the return message critically', 'A tool completed message is only one observation. The provider can continue responding, but the independent check still matters.'], ['Check the complete artifact', 'Use node verify.mjs and the expected diff to decide success; the same contract works with another model.']] },
    recovery: { title: 'Separate DeepSeek call IDs from Pi session branches', nodes: [item('Resume the Pi host', 'terminal', 'DeepSeek does not resume the developer’s filesystem. Pi provides the saved-session interface.', pi.resume), item('Pi JSONL session', 'session-tree', 'The conversation tree preserves relationships among recorded entries.', pi.session), item('Provider call correlation', 'api-gateway', 'tool_call_id connects the host observation to the provider’s original request.', deepseek.result), item('Three identity roles', 'checkpoint-bridge', 'Conversation entry identity, provider call correlation and application deduplication solve different problems.', deepseek.session), output(), check()], beats: [['Resume the host session', 'Select the intended Pi conversation and model context.'], ['Inspect recorded history', 'The session tree can tell you which observation was recorded, but it cannot prove that an unrecorded effect never happened.'], ['Preserve provider correlation', 'A tool result references its original call ID so the model can understand the observation. This is not a receiver-side deduplication contract.'], ['Reconcile an ambiguous effect', 'Use the actual application’s operation identity and stored state when a receipt is missing. Do not treat tool_call_id as automatic idempotency.'], ['Re-read before retrying', 'Inspect help.md and rerun the verifier. If the intended effect already exists, continue from verified state rather than blindly repeating it.']] },
  },
};

const providerMeta: Record<PublicProvider, { name: string; layout: StageLayout; positions: [number, number, number][]; sources: StageSpec['sources'] }> = {
  pi: { name: 'Pi', layout: 'pi-workbench', positions: [[-5,0,0],[-3,1.7,0],[-.5,0,0],[0,2.8,-1],[2.7,0,0],[5,1,0]], sources: [{ title: 'Pi coding harness', url: urls.pi }, { title: 'Pi extension events', url: urls.extensions }, { title: 'Pi session format', url: urls.sessions }, { title: 'Current Pi package manifests', url: urls.packages }] },
  codex: { name: 'Codex', layout: 'codex-sandbox', positions: [[-5,1.5,0],[-5,-1.3,0],[-1.5,1,0],[1,0,0],[3.7,1.5,0],[3.7,-1.5,0]], sources: [{ title: 'Codex CLI', url: urls.codex }, { title: 'AGENTS.md discovery', url: urls.agents }, { title: 'Sandbox and approval configuration', url: urls.sandbox }] },
  claude: { name: 'Claude Code', layout: 'claude-hooks', positions: [[-5,0,0],[-3,2,0],[-1,0,0],[1.5,2,0],[3.5,0,0],[5,-2,0]], sources: [{ title: 'Project memory', url: urls.claude }, { title: 'Claude Code hooks', url: urls.claudeHooks }, { title: 'Permission rules', url: urls.claudePermissions }, { title: 'Claude Code CLI', url: urls.claudeCli }] },
  factory: { name: 'Factory Droid', layout: 'droid-pipeline', positions: [[-5,0,0],[-3,0,0],[-1,0,0],[1,0,0],[3,0,0],[5,0,0]], sources: [{ title: 'Droid AGENTS.md', url: urls.factory }, { title: 'Factory hook events', url: urls.factoryHooks }, { title: 'Droid CLI', url: urls.factoryCli }] },
  deepseek: { name: 'DeepSeek with Pi', layout: 'deepseek-wire', positions: [[-5,1.8,0],[-2.8,1.8,0],[1,1.8,0],[3.5,-1,0],[.5,-2,0],[-3,-2,0]], sources: [{ title: 'DeepSeek tool calls', url: urls.deepseek }, { title: 'Pi providers and tools', url: urls.pi }, { title: 'Pi extension events', url: urls.extensions }, { title: 'Pi session format', url: urls.sessions }] },
};

/** A different provider topology, inspectable code, and five causal frames for each topic. */
export function providerStage(provider: PublicProvider, topic: StageTopic): StageSpec {
  const meta = providerMeta[provider], story = stories[provider][topic];
  const nodes: StageNode[] = story.nodes.map(([label, asset, detail, snippet], index) => ({ id: `p${index}`, label, asset, detail, code: { ...snippet, highlight: [...(snippet.highlight || [1])] }, position: [meta.positions[index][0], 0, meta.positions[index][1]] }));
  if (topic === 'permissions') {
    nodes[4] = { ...nodes[4], label: 'Unchanged task document', asset: 'editor', detail: 'The denied proposal did not execute. The typo remains; containment did not complete the user task.', code: { ...original, highlight: [1, 3] } };
    nodes[5] = { ...nodes[5], label: 'Containment evidence · task pending', detail: 'This is the authored denied state, not a passing verifier or a claim that a live operation was blocked.', code: pseudo('denied-frame.txt · teaching state', 'Outside-scope proposal: denied before execution\nOutside-scope effect: none in this teaching state\nhelp.md: original typo remains\nTask acceptance: not satisfied\nNext work: propose the authorized correction, then verify it', meta.sources[0].url, [1, 2, 3, 4]) };
  }
  const linkLabels = topic === 'recovery' ? ['restore context', 'recover observation', 'reconcile identity', 'inspect current effect', 'revalidate'] : topic === 'permissions' ? ['scope', 'propose', 'check before dispatch', 'permitted effect only', 'verify outcome'] : ['task context', 'load / propose', 'runtime seam', 'bounded operation', 'acceptance evidence'];
  const focusIndices = [0, 1, 2, 3, 5];
  return {
    id: `${provider}-${topic}`, title: story.title,
    subtitle: `${meta.name} · ${topic} · inspect the real configuration seam and the teaching artifact`,
    provider: meta.name, layout: meta.layout, nodes,
    links: nodes.slice(1).map((node, index) => ({ from: `p${index}`, to: node.id, label: linkLabels[index], kind: topic === 'recovery' && index < 3 ? 'checkpoint' : index === 0 ? 'context' : index === 1 ? 'proposal' : index === 4 ? 'result' : 'action' })),
    frames: story.beats.map(([title, explanation], index) => {
      const at = focusIndices[index], blocked = story.blocked === at;
      const deniedEvidence = topic === 'permissions' && index === 4;
      const focus = index === 4 ? ['p5', 'p4'] : [`p${at}`];
      return { id: `${provider}-${topic}-${index + 1}`, title: deniedEvidence ? 'Inspect containment; the task is still pending' : title, explanation: deniedEvidence ? `${meta.name} has not executed the denied proposal in this teaching state. The original typo remains. Containment is evidence about the boundary, not a passing artifact check; a new authorized correction and verification are still required.` : explanation, focus,
        route: Array.from({ length: (deniedEvidence ? story.blocked! : at) + 1 }, (_, i) => `p${i}`),
        code: { ...nodes[at].code, highlight: [...(nodes[at].code.highlight || [1])] },
        states: Object.fromEntries(nodes.map((node, i) => [node.id, deniedEvidence ? i === story.blocked ? 'blocked' : i === at ? 'active' : i < story.blocked! ? 'passed' : 'ready' : i === at ? blocked ? 'blocked' : index === 4 ? 'passed' : 'active' : i < at ? 'passed' : 'ready'])),
        packet: blocked ? 'Proposal stopped before effect' : deniedEvidence ? 'Containment observed · task pending' : index === 4 ? 'Inspect acceptance evidence' : topic === 'recovery' ? 'Restore and revalidate' : 'Follow this handoff',
      };
    }),
    sources: meta.sources.map(source => ({ ...source })),
    note: 'Authored educational cutaway; no provider is executed. Workshop file excerpts are real. API examples use documented fields but are not installed; wire payloads and pseudocode are labeled. Hook scripts named in configuration must be implemented and reviewed separately. A session ID or tool-call ID does not provide business-operation idempotency. Sources reviewed 7 September 2026.',
  };
}
